<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <NoWarn>$(NoWarn);SYSLIB0057</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../references/Zamboni-BlazeSDK/Blaze3SDK/Blaze3SDK.csproj"
                      AdditionalProperties="TreatWarningsAsErrors=false" />
  </ItemGroup>
</Project>
